import type { RedpenReport, VerificationResult, VerificationStatus } from "../core/types.js";

const symbols: Record<VerificationStatus, string> = { proven: "✓", failed: "✗", unverified: "?" };

// Claims, titles, reasons, and command names are untrusted. Keep each value on one
// line and prevent it from introducing Markdown links, headings, or HTML.
function safe(value: string): string {
  return value.replace(/[\x00-\x1f\x7f-\x9f\u202a-\u202e\u2066-\u2069]+/g, " ").replace(/\s+/g, " ").trim()
    .replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;")
    .replace(/([\\`*_{}\[\]|])/g, "\\$1");
}

function resultLines(result: Pick<VerificationResult, "status" | "reason" | "evidence">, label: string): string[] {
  const evidence = [...new Set(result.evidence.map((item) => item.summary))];
  return [
    `- ${symbols[result.status]} **${result.status.toUpperCase()}** — ${safe(label)}`,
    `  - ${safe(result.reason)}`,
    ...evidence.slice(0, 3).map((summary) => `  - Evidence: ${safe(summary)}`),
    ...(evidence.length > 3 ? [`  - ${evidence.length - 3} more evidence item(s) in \`.redpen/report.json\`.`] : []),
  ];
}

export function renderMarkdown(report: RedpenReport, stale = false): string {
  const verdict = stale ? "CHECK NEEDED" : report.verdict === "done" ? "DONE" : "NOT DONE";
  const unresolvedClaims = report.agentClaimSummary?.unverified ?? report.agentClaimResults.filter((item) => item.status === "unverified").length;
  const verdictDetail = !stale && report.verdict === "done" && unresolvedClaims > 0
    ? ` (${unresolvedClaims} agent ${unresolvedClaims === 1 ? "claim remains" : "claims remain"} unverified)` : "";
  const lines = [
    "# Redpen evidence receipt",
    "",
    ...(report.task ? [`**Task:** ${safe(report.task.description)}`, ""] : []),
    `**Verdict:** ${verdict}${verdictDetail}`,
    `**Checked:** ${safe(report.timestamp)}`,
    `**Summary:** ${report.summary.proven} proven · ${report.summary.failed} failed · ${report.summary.unverified} unverified`,
    `**Claim policy:** ${report.verificationPolicy?.requireAllClaims ? "Every agent claim must be proven" : "Required criteria must be proven; contradicted claims block DONE"}`,
    "",
  ];
  if (stale || report.evidenceFreshness?.stale) lines.push("> Evidence is stale. Repository files changed since this check; run `redpen check` again before sharing this receipt.", "");
  lines.push("## Definition of done", "");
  for (const [index, result] of report.definitionOfDoneResults.entries()) {
    const kind = report.definitionOfDone[index]?.required === false ? "advisory" : "required";
    lines.push(...resultLines(result, `${result.title} (${kind})`));
  }
  if (report.agentClaimResults.length > 0) {
    lines.push("", "## Agent claims", "");
    for (const result of report.agentClaimResults) lines.push(...resultLines(result, `“${result.originalText}”`));
  }
  if (report.proposedCriteria?.length) lines.push("", `${report.proposedCriteria.length} proposed criteria await acceptance; they were not verified.`);
  lines.push("", "_Generated by Redpen. Command output and the agent's full completion are omitted; review the receipt before sharing._");
  return `${lines.join("\n")}\n`;
}
